# Generated by Django 6.0.1 on 2026-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="model_type",
            field=models.CharField(
                choices=[("lightgbm", "LightGBM"), ("xgboost", "XGBoost")],
                default="lightgbm",
                max_length=20,
            ),
        ),
    ]
